---
# To avoid directly editing this file, create a vcs file called 
# config.yml in a different top level directory and 
# create a symbolic link to it in the same directory as this file. 
# Then copy the configurations you wish to change from here into 
# config.yml
# 
# For example
# config.yml
# ================
#
# nginx_conf_sites:
#  web1:
#    file_name: mysite.conf 
#    template_name: template-drupal8.conf.j2
#    template_params:
#      server_name: mysite.test      
#      root: /var/www/html/mysite/docroot    
#      php_version: 7.1 


# Available `vagrant_box` values include:
vagrant_box: geerlingguy/ubuntu1604

vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs
vagrant_gui: false

# If you need to run multiple instances of Badzilla VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: your-dev-box
vagrant_machine_name: badzilla-vm
vagrant_ip: 192.168.77.77

# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/ for more.
# vagrant_synced_folders:
#   - local_path: .
#     destination: /var/www/html
#     type: nfs
#     create: true

# MySQL user
mysql_user_home: /root
mysql_user_name: drupal
mysql_user_password: drupal

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 1

# Ensure vagrant plugins are installed.
vagrant_plugins:
  - name: vagrant-vbguest
  - name: vagrant-hostsupdater

# Minimum required versions.
badzillavm_vagrant_version_min: '1.8.6'
badzillavm_ansible_version_min: '2.4'

# Force use of ansible_local provisioner, even if Ansible is installed on host.
force_ansible_local: false

# Firewall settings
firewall_enabled: true
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
firewall_log_dropped_packets: false
firewall_disable_firewalld: true
firewall_disable_ufw: true

# Add nginx virtual hosts
nginx_conf_sites:
  web1:
    file_name: site1.conf 
    template_name: template-drupal6.conf.j2
    template_params:
      server_name: site1.test      
      root: /var/www/html/site1/docroot    
      php_version: 5.6
# web2:
#   file_name: site2.conf       
#   template_name: template-drupal7.conf.j2
#   template_params:
#     server_name: site2.test      
#     root: /var/www/html/site2/docroot    
#     php_version: 7.0

# Other nginx settings
nginx_remove_default_vhost: true


