---

- hosts: all
  become: yes

  # *BUG* Currently the config.yml is needed and has to be created by the user
  # Requires investigation - find a neater alternative
  vars_files:
    - default.config.yml
    - config.yml

  vars:

    - name: Set the nginx config for pimpmylog 
      pimp_my_log_site:
        pimpmylog:
          file_name: pimpmylog.conf
          template_name: template-php.conf.j2
          template_params:
            server_name: pimpmylog.test      
            root: /opt/pimpmylog
            php_version: 7.1


  pre_tasks:

    - include_tasks: "tasks/init-{{ ansible_os_family }}.yml"

    - name: Merge all the vhosts together
      set_fact: 
        all_vhosts: "{{ [ user_vhosts_conf ] }}"


  roles:

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 7.2
      php_cli_ondrej_update_alternatives: true
      php_cli_ondrej_mods_present:
        - name: json
        - name: xml
        - name: readline
        - name: mysql
        - name: memcached
        - name: msgpack
        - name: mbstring
        - name: gd
        - name: curl
      php_cli_ondrej_install:
        -  php7.2-xdebug
        -  php7.2-fpm 

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 7.1
      php_cli_ondrej_update_alternatives: true   
      php_cli_ondrej_install:
        -  php7.1-xdebug   
        -  php7.1-fpm   

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 7.0
      php_cli_ondrej_update_alternatives: true  
      php_cli_ondrej_install:
        -  php7.0-xdebug    
        -  php7.0-fpm    

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 5.6
      php_cli_ondrej_update_alternatives: true
      php_cli_ondrej_install:
        -  php5.6-xdebug
        -  php5.6-xhprof        
        -  php5.6-fpm


    - role: geerlingguy.nginx
    - role: TroodoNmike.nginx-conf
      nginx_conf_default_path: /etc/nginx/sites-available
      nginx_conf_default_port: 80
      nginx_conf_sites: "{{ all_vhosts }}"


    - role: geerlingguy.memcached
    - role: geerlingguy.nodejs

    - role: geerlingguy.mysql
      mysql_packages:
        - mariadb-client
        - mariadb-server

    - role: geerlingguy.composer
      composer_keep_updated: true

    # See https://github.com/drush-ops/drush-launcher/issues/33 
    # on how to use drush on non-composer Drupal projects  
    - role: geerlingguy.drush
      drush_launcher_install: yes
      drush_launcher_version: "0.5.1"

    # VMs are naturally unsafe places...
    - role: geerlingguy.firewall

    # Jenkins and its dependency, Java
    - role: geerlingguy.java
    - role: geerlingguy.jenkins

    # Pretty logs - this needs chmod 777 in install directory
    - role: geerlingguy.pimpmylog
      pimpmylog_install_dir: /opt/pimpmylog
      pimpmylog_grant_all_privs: yes

    # Capture outgoing mail - needs daemonize
    - role: geerlingguy.daemonize 
    - role: geerlingguy.mailhog
      mailhog_install_dir: /opt/mailhog


  tasks: 

    # Set symlinks to nginx sites-available directory
    - name: Get a list of all vhosts
      find:
        paths: /etc/nginx/sites-available
        patterns: "*.conf"
        file_type: file
      register: find

    - name: Apply symlinks in sites-enabled
      file:
        dest: /etc/nginx/sites-enabled/{{ item.path | basename }}
        src: "{{ item.path }}"
        state: link
        force: yes
      with_items: "{{ find.files }}"

    - name: Set sendmail path in php.ini files
      ini_file:
        path: "{{ item }}"
        section: "mail function"
        option: sendmail_path
        value: /opt/mailhog/mhsendmail
      loop:
        - /etc/php/5.6/cli/php.ini
        - /etc/php/5.6/fpm/php.ini
        - /etc/php/7.0/cli/php.ini
        - /etc/php/7.0/fpm/php.ini
        - /etc/php/7.1/cli/php.ini
        - /etc/php/7.1/fpm/php.ini
        - /etc/php/7.2/cli/php.ini
        - /etc/php/7.2/fpm/php.ini  

    # - name: debug the sites
    #   debug: 
    #     var: all_vhosts  

  post_tasks:
  
    - name: Restart nginx to prevent connection refused bug
      service:
        name: nginx
        state: restarted      


