---

- hosts: all
  become: yes



  roles:

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 7.2
      php_cli_ondrej_update_alternatives: true
      php_cli_ondrej_mods_present:
        - name: json
        - name: xml
        - name: readline
        - name: mysql
        - name: memcached
        - name: msgpack
        - name: mbstring
        - name: gd
        - name: curl
      php_cli_ondrej_install:
        -  php7.2-xdebug
        -  php7.2-fpm 

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 7.1
      php_cli_ondrej_update_alternatives: true   
      php_cli_ondrej_install:
        -  php7.1-xdebug
        -  php7.1-fpm   

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 7.0
      php_cli_ondrej_update_alternatives: true  
      php_cli_ondrej_install:
        -  php7.0-xdebug   
        -  php7.0-fpm    

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 5.6
      php_cli_ondrej_update_alternatives: true
      php_cli_ondrej_install:
        -  php5.6-xdebug 
        -  php5.6-fpm


    - role: geerlingguy.nginx
    - role: TroodoNmike.nginx-conf
    - role: geerlingguy.memcached

    - role: geerlingguy.mysql
      mysql_packages:
        - mariadb-client
        - mariadb-server

