---

- hosts: all
  become: yes

  # *IMPORTANT* The user must create the config.yml file. See README.md
  vars_files:
    - vars/main.yml
    - default.config.yml
    - config.yml


  pre_tasks:

    - include_tasks: "tasks/init-{{ ansible_os_family }}.yml"

    - name: Merge all the vhosts together
      set_fact: 
        all_vhosts: "{{ [ user_vhosts_conf ] }} + {{ [ _devtool_docroots ] }}"


  roles:

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 7.2
      php_cli_ondrej_update_alternatives: true
      php_cli_ondrej_mods_present:
        - name: json
        - name: xml
        - name: readline
        - name: mysql
        - name: memcached
        - name: msgpack
        - name: mbstring
        - name: gd
        - name: curl
      php_cli_ondrej_install:
        -  php7.2-xdebug
        -  php7.2-fpm
        -  php7.2-ssh2

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 7.1
      php_cli_ondrej_install:
        -  php7.1-xdebug   
        -  php7.1-fpm
        -  php7.1-ssh2 

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 7.0
      php_cli_ondrej_install:
        -  php7.0-xdebug    
        -  php7.0-fpm
        -  php7.0-ssh2  

    - role: Oefenweb.php-cli-ondrej
      php_cli_ondrej_version: 5.6
      php_cli_ondrej_install:
        -  php5.6-xdebug
        -  php5.6-xhprof        
        -  php5.6-fpm
        -  php5.6-ssh2


    - role: geerlingguy.nginx
    - role: TroodoNmike.nginx-conf
      nginx_conf_default_path: /etc/nginx/sites-available
      nginx_conf_default_port: 80
      nginx_conf_sites: "{{ all_vhosts }}"


    - role: geerlingguy.memcached
    - role: geerlingguy.nodejs

    - role: geerlingguy.mysql
      mysql_packages:
        - mariadb-client
        - mariadb-server

    - role: geerlingguy.composer
      composer_keep_updated: true

    # See http://badzilla.co.uk/drupal-7-drush-loader-and-non-composer-project
    # on how to use drush on non-composer Drupal projects  
    - role: geerlingguy.drush
      drush_launcher_install: yes
      drush_launcher_version: "0.5.1"

    # VMs are naturally unsafe places...
    - role: geerlingguy.firewall

    # Jenkins and its dependency, Java
    - role: geerlingguy.java
    - role: geerlingguy.jenkins

    # Pretty logs - this needs chmod 777 in install directory
    - role: geerlingguy.pimpmylog
      pimpmylog_install_dir: /opt/pimpmylog
      pimpmylog_grant_all_privs: yes

    # Capture outgoing mail - needs daemonize
    - role: geerlingguy.daemonize 
    - role: geerlingguy.mailhog
      mailhog_install_dir: /opt/mailhog

    # Adminer for those without access to Sequel Pro
    - role: geerlingguy.adminer
      adminer_install_dir: /opt/adminer
      adminer_install_filename: index.php

    # Bash aliases. Used primarily for switching CLI PHP versions
    - role: igor_mukhin.bash_aliases
      sudo: false


  tasks: 

    # Set symlinks to nginx sites-available directory
    - name: Get a list of all vhosts
      find:
        paths: /etc/nginx/sites-available
        patterns: "*.conf"
        file_type: file
      register: find

    - name: Apply symlinks in sites-enabled
      file:
        dest: /etc/nginx/sites-enabled/{{ item.path | basename }}
        src: "{{ item.path }}"
        state: link
        force: yes
      with_items: "{{ find.files }}"

    - name: Inject PHP settings into relevant version ini files
      include_tasks: tasks/php_ini.yml 

    - name: set timezone to default value
      timezone:
        name: "{{ user_timezone }}"

    - name: patch .bashrc to customise the prompt
      patch:
        src: patches/bashrc.patch
        dest: /home/vagrant/.bashrc  

    - name: Create the dashboard
      import_tasks: tasks/dashboard.yml

    - name: Check if xhprof library created with wrong directory name
      stat:    
        path: /usr/share/php-xhprof/lib
      register: stat_result

    - name: If xhprof library name wrong then mv to correct name
      command: mv /usr/share/php-xhprof/lib /usr/share/php-xhprof/xhprof_lib
      when: stat_result.stat.exists == True

  post_tasks:
  
    - name: Restart nginx / FPM to prevent connection refused bug and ini changes to take effect
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - nginx
        - php5.6-fpm
        - php7.0-fpm
        - php7.1-fpm
        - php7.2-fpm


