---
- src: Oefenweb.php-cli-ondrej
  version: v2.2.3

- src: geerlingguy.nginx
  version: 2.6.0

- src: TroodoNmike.nginx-conf

- src: geerlingguy.mysql
  version: 2.9.0

- src: geerlingguy.memcached
  version: 1.0.8

- src: geerlingguy.composer
  version: 1.7.0

- src: geerlingguy.nodejs
  version: 4.2.0 

- src: geerlingguy.drush
  version: 3.1.1