---
galaxy_info:
  author: devsoul
  role_name: phing
  description: Install Phing on your Linux machine
  company: Devhost Ltd.
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
    - name: GenericBSD
      versions:
        - all
    - name: GenericUNIX
      versions:
        - all
  galaxy_tags:
    - phing
    - php
    - phpdev
    - phptools
    - phpapps
    - web
    - development

dependencies: []
