---
- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=86400

- name: Install required dependencies.
  apt: "name={{ item }} state=present"
  with_items:
    - curl
    - python-apt
    - python-pycurl
    - sudo
    - unzip
    - make