---


- name: Set sendmail path in php.ini files
  ini_file:
    path: "{{ item }}"
    section: "mail function"
    option: sendmail_path
    value: /opt/mailhog/mhsendmail
  loop:
    - /etc/php/5.6/cli/php.ini
    - /etc/php/5.6/fpm/php.ini
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/fpm/php.ini
    - /etc/php/7.1/cli/php.ini
    - /etc/php/7.1/fpm/php.ini
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/fpm/php.ini 


- name: memory_limit setting
  ini_file:
    path: "{{ item.path }}"
    section: PHP
    option: memory_limit
    value: "{{ item.value }}"
  loop:
    -  { path: "{{ php5_6_cli.path }}", value: "{{ php5_6_cli.memory_limit }}" }
    -  { path: "{{ php5_6_web.path }}", value: "{{ php5_6_web.memory_limit }}" }
    -  { path: "{{ php7_0_cli.path }}", value: "{{ php7_0_cli.memory_limit }}" }
    -  { path: "{{ php7_0_web.path }}", value: "{{ php7_0_web.memory_limit }}" }
    -  { path: "{{ php7_1_cli.path }}", value: "{{ php7_1_cli.memory_limit }}" }
    -  { path: "{{ php7_1_web.path }}", value: "{{ php7_1_web.memory_limit }}" }
    -  { path: "{{ php7_2_cli.path }}", value: "{{ php7_2_cli.memory_limit }}" }
    -  { path: "{{ php7_2_web.path }}", value: "{{ php7_2_web.memory_limit }}" }       
