---


- name: Set sendmail path in php.ini files
  ini_file:
    path: "{{ item }}"
    section: "mail function"
    option: sendmail_path
    value: /opt/mailhog/mhsendmail
  loop:
    - /etc/php/5.6/cli/php.ini
    - /etc/php/5.6/fpm/php.ini
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/fpm/php.ini
    - /etc/php/7.1/cli/php.ini
    - /etc/php/7.1/fpm/php.ini
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/fpm/php.ini 


- name: php5.6 cli
  ini_file:
    path: /etc/php/5.6/cli/php.ini
    section: PHP
    option: memory_limit
    value: "{{ php5_6_cli.memory_limit }}"

- name: php5.6 web
  ini_file:
    path: /etc/php/5.6/fpm/php.ini
    section: PHP
    option: memory_limit
    value: "{{ php5_6_web.memory_limit }}"

- name: php7.0 cli
  ini_file:
    path: /etc/php/7.0/cli/php.ini
    section: PHP
    option: memory_limit
    value: "{{ php7_0_cli.memory_limit }}"

- name: php7.0 web
  ini_file:
    path: /etc/php/7.0/fpm/php.ini
    section: PHP
    option: memory_limit
    value: "{{ php7_0_web.memory_limit }}"

- name: php7.1 cli
  ini_file:
    path: /etc/php/7.1/cli/php.ini
    section: PHP
    option: memory_limit
    value: "{{ php7_1_cli.memory_limit }}"

- name: php7.1 web
  ini_file:
    path: /etc/php/7.1/fpm/php.ini
    section: PHP
    option: memory_limit
    value: "{{ php7_1_web.memory_limit }}" 

- name: php7.2 cli
  ini_file:
    path: /etc/php/7.2/cli/php.ini
    section: PHP
    option: memory_limit
    value: "{{ php7_2_cli.memory_limit }}"

- name: php7.2 web
  ini_file:
    path: /etc/php/7.2/fpm/php.ini
    section: PHP
    option: memory_limit
    value: "{{ php7_2_web.memory_limit }}"            